version: '3.5'

services:
  postgres:
    container_name: postgres_flatup
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: flatupdb
      PGDATA: 
    ports:
      - "5432:5432"
    restart: unless-stopped